use std::fs;
use std::path::PathBuf;

const FILES: &[(&str, &str)] = &[
    (
        "package.json",
        r#"{
  "name": "my-plec-app",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "plec dev",
    "build": "plec build",
    "serve": "plec serve dist"
  },
  "dependencies": {
    "plec": "file:../plec"
  },
  "devDependencies": {
    "esbuild": "^0.27.4"
  }
}
"#,
    ),
    (
        "plec.toml",
        r#"[app]
title = "My Plec App"
description = "A Plec application."

[server]
entry = "src/server.ts"

[client]
styles = "/assets/styles.css"
"#,
    ),
    (
        "src/router.tsx",
        r#"import { createRouter } from '@plec/core';
import { Route as rootRoute } from './routes/index';

export const router = createRouter({
  routeTree: rootRoute,
});

export default router;
"#,
    ),
    (
        "src/routes/index.tsx",
        r#"import { createRootRoute } from '@plec/core';
import { Home } from './home';

export const Route = createRootRoute({
  component: Home,
});
"#,
    ),
    (
        "src/routes/home.tsx",
        r#"export function Home() {
  return <main><h1>My Plec App</h1><p>Welcome to Plec.</p></main>;
}
"#,
    ),
    (
        "src/client.tsx",
        r#"import { startPlecRouter } from '@plec/core/browser';

const root = document.querySelector<HTMLElement>('#app');
if (!root) throw new Error('The Plec application root is missing.');

await startPlecRouter({
  root,
  manifestUrl: '/route-manifest.json',
  graphUrl: (graphId) =>
    `/graphs/${graphId.replace(/[\/\\]/g, '--').replace('#', '--')}.json`,
});
"#,
    ),
    (
        "src/server.ts",
        r#"import type { AppRequestHandler } from '@plec/core/server';

export const handleRequest: AppRequestHandler = async (request) => {
  const url = new URL(request.url);
  return new Response(JSON.stringify({ ok: true, path: url.pathname }), {
    headers: { 'content-type': 'application/json' },
  });
};
"#,
    ),
    (
        "src/styles.css",
        r#":root {
  font-family: system-ui, sans-serif;
  color: #1f2937;
  background: #f8fafc;
}

body {
  margin: 0;
}

main {
  max-width: 52rem;
  margin: 4rem auto;
  padding: 0 1.5rem;
}
"#,
    ),
    (".gitignore", "node_modules/\ndist/\n"),
    (
        "README.md",
        r#"# My Plec App

Minimal Plec application generated by `plec init`.

Install dependencies, then build and serve:

```sh
npm install
npm run build
npm run serve
```

The `plec` dependency points at a sibling release artifact in `../plec`.
Keep the generated app beside the release artifact, or change that dependency
to the release package location before installing.

`src/server.ts` owns application API behavior. The native Plec host owns HTTP,
SSR, asset serving, and the Node sidecar lifecycle.
"#,
    ),
];

pub fn run(directory: PathBuf, force: bool) -> Result<(), Box<dyn std::error::Error>> {
    if directory.exists() && !directory.is_dir() {
        return Err(format!("init target is not a directory: {}", directory.display()).into());
    }
    if directory.is_dir() && !force && fs::read_dir(&directory)?.next().is_some() {
        return Err(format!(
            "refusing to initialize non-empty directory {}; pass --force to continue",
            directory.display()
        )
        .into());
    }

    fs::create_dir_all(&directory)?;
    let name = package_name(&directory);
    let title = name
        .split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ");
    for (relative, contents) in FILES {
        let path = directory.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let rendered = contents
            .replace("my-plec-app", &name)
            .replace("My Plec App", &title);
        fs::write(path, rendered)?;
    }

    println!("Created Plec application in {}", directory.display());
    println!("Next steps:");
    println!("  cd {}", directory.display());
    println!("  npm install");
    println!("  npm run dev");
    Ok(())
}

fn package_name(directory: &std::path::Path) -> String {
    directory
        .file_name()
        .and_then(|name| name.to_str())
        .map(|name| {
            name.chars()
                .map(|character| {
                    if character.is_ascii_alphanumeric() || character == '-' {
                        character.to_ascii_lowercase()
                    } else {
                        '-'
                    }
                })
                .collect::<String>()
        })
        .filter(|name| !name.trim_matches('-').is_empty())
        .map(|name| name.trim_matches('-').to_owned())
        .unwrap_or_else(|| "plec-app".to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn creates_scaffold_and_preserves_unowned_files_with_force() {
        let directory = tempfile::tempdir().unwrap();
        let target = directory.path().join("app");
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("keep.txt"), "keep").unwrap();

        run(target.clone(), true).unwrap();

        assert!(target.join("src/router.tsx").is_file());
        assert_eq!(fs::read_to_string(target.join("keep.txt")).unwrap(), "keep");
        assert!(fs::read_to_string(target.join("src/server.ts"))
            .unwrap()
            .contains("AppRequestHandler"));
    }

    #[test]
    fn rejects_non_empty_directory_without_force() {
        let directory = tempfile::tempdir().unwrap();
        fs::write(directory.path().join("existing.txt"), "existing").unwrap();

        let error = run(directory.path().to_path_buf(), false).unwrap_err();

        assert!(error.to_string().contains("non-empty directory"));
    }
}
