import { Fragment, jsx, jsxs } from './client/jsx';
import { createRoot } from './client/root/create-root';
import { useState } from './client/state/use-state';
import { useMutation } from './client/state/use-mutation';
import { useHostRef, useRef } from './client/state/use-ref';
import { useReaction } from './client/state/use-reaction';
import { useListener } from './client/state/use-listener';
import { createRootRoute, createRoute, createRouter, Link, notFound, Outlet, redirect, RouterProvider, useNavigate } from './routes/router';
import { useLocation } from './routes/use-location';
import { cookie } from './cookie';
import { action } from './server';
export { Fragment, jsx, jsxs, createRoot, useState, useMutation, useRef, useHostRef, useReaction, useListener, useLocation, cookie, action, useNavigate, createRootRoute, createRoute, createRouter, redirect, notFound, RouterProvider, Link, Outlet, };
export type { PlecChild, PlecComponent, PlecNode } from './client/jsx';
export type { PlecMutation } from './client/state/use-mutation';
export type { PlecController } from './client/root/root-state';
export type { RedirectOptions, LoaderContext, PendingMode, RouteMetadata, RouteOptions, RouteDefinition, RouteParams, RouteSearch, } from './routes/router';
export { PlecNotFoundOutcome, PlecRedirectOutcome, } from './routes/router';
export declare const Plec: {
    createRoot: typeof createRoot;
    useState: typeof useState;
    useMutation: typeof useMutation;
    useRef: typeof useRef;
    useHostRef: typeof useHostRef;
    useReaction: typeof useReaction;
    useListener: typeof useListener;
    useLocation: typeof useLocation;
    cookie: {
        getSync(_name: string): string | null;
        get(_name: string): Promise<string | null>;
        set(_name: string, _value: string, _options?: import("./cookie").CookieOptions): Promise<void>;
        delete(_name: string, _options?: import("./cookie").CookieOptions): Promise<void>;
    };
    action: typeof action;
    useNavigate: typeof useNavigate;
    createRootRoute: typeof createRootRoute;
    createRoute: typeof createRoute;
    createRouter: typeof createRouter;
    RouterProvider: import(".").PlecComponent;
    Link: import(".").PlecComponent;
    Outlet: import(".").PlecComponent;
    jsx: typeof jsx;
    jsxs: typeof jsx;
    Fragment: typeof Fragment;
};
