[package]
name = "plec-action"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = ["plec-schema/serde"]

[dependencies]
plec-ir = { path = "../plec-ir", version = "0.1.0", default-features = false }
plec-schema = { path = "../plec-schema", version = "0.1.0", default-features = false }

[dev-dependencies]
serde_json.workspace = true
plec-schema = { path = "../plec-schema", version = "0.1.0", features = ["serde"] }
