/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class NativeActionResponse {
  get status(): number
  get headers(): Array<NativeHeader>
  body(): ReadableStream<Buffer>
}

export declare class NativeCallbackPermit {
  release(): void
}

export declare class NativeCallbacks {
  loadApplication(options: NativeApplicationOptions): Promise<PlecApplication>
}

export declare class NativeCancellation {
  cancel(): void
}

export declare class NativeDocumentResponse {
  get status(): number
  get headers(): Array<NativeHeader>
  body(): ReadableStream<Buffer>
}

export declare class PlecApplication {
  tryAcquireCallback(): NativeCallbackPermit | null
  createCancellation(): NativeCancellation
  handleDocument(request: NativeRequest, requestCancellation: NativeCancellation): Promise<NativeDocumentResponse>
  handleAction(request: NativeRequest, body: ReadableStream<Buffer>, cancelBody: (arg: string) => Promise<undefined>, requestCancellation: NativeCancellation): Promise<NativeActionResponse>
  close(): Promise<void>
}

export declare function createCallbacks(renderHost: (arg: string) => Promise<string>, invokeAction: (arg: string) => Promise<string>): NativeCallbacks

export declare function maxRequestBodyBytes(): number

export interface NativeApplicationOptions {
  artifactPath: string
  clientScript?: string
  clientStyles?: Array<string>
  stylesHref?: string
  preloads?: Array<string>
  customElements?: Array<string>
  title?: string
  description?: string
  development?: boolean
}

export interface NativeHeader {
  name: string
  value: string
}

export interface NativeRequest {
  method: string
  url: string
  headers: Array<NativeHeader>
}
