[package]
name = "plec-build"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
brotli = { workspace = true }
plec-compiler = { path = "../plec-compiler", version = "0.1.0" }
plec-ir = { path = "../plec-ir", version = "0.1.0" }
plec-model = { path = "../plec-model", version = "0.1.0" }
plec-parser = { path = "../plec-parser", version = "0.1.0" }
swc_ecma_ast.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
