[package]
name = "plec-cli"
version.workspace = true
edition.workspace = true

[dependencies]
plec-inspect = { path = "../plec-inspect" }
plec-ir = { path = "../plec-ir" }
plec-parser = { path = "../plec-parser" }
plec-sema = { path = "../plec-sema" }
plec-compiler = { path = "../plec-compiler" }
clap = { workspace = true }
pollster = { workspace = true }
serde_json = { workspace = true }
[[bin]]
name = "plec"
path = "src/main.rs"