[package]
name = "plec-cli"
version.workspace = true
edition.workspace = true

[dependencies]
plec-inspect = { path = "../plec-inspect" }
plec-ir = { path = "../plec-ir" }
plec-parser = { path = "../plec-parser" }
plec-model = { path = "../plec-model" }
plec-compiler = { path = "../plec-compiler" }
plec-build = { path = "../plec-build" }
clap = { workspace = true }
pollster = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
brotli = { workspace = true }
sha2 = { workspace = true }
[[bin]]
name = "plec"
path = "src/main.rs"

[build-dependencies]
dotenvy = "0.15.7"
