[package]
name = "plec-server-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes = "1"
http = "1"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest = { workspace = true, features = ["stream"] }
futures-util.workspace = true
thiserror.workspace = true
indexmap.workspace = true
plec-ir = { path = "../plec-ir", version = "0.1.0" }
plec-schema = { path = "../plec-schema", version = "0.1.0" }
plec-action = { path = "../plec-action", version = "0.1.0" }
plec-eval = { path = "../plec-eval", version = "0.1.0" }

[dev-dependencies]
tempfile.workspace = true
