use std::{cell::RefCell, collections::{HashMap, HashSet}, rc::Rc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use wasm_bindgen::{prelude::*, closure::Closure, JsCast};
use web_sys::{Document, Element, Event, HtmlElement, HtmlInputElement, MediaQueryList, Node};

#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct ApplicationIr { root_element_id:String, #[serde(default)] revision:Option<String>, elements:Vec<ElementNode>, texts:Vec<TextNode>, #[serde(default)] bindings:Vec<BindingNode>, #[serde(default)] expressions:Vec<ExpressionNode>, #[serde(default)] events:Vec<EventNode>, #[serde(default)] loops:Vec<LoopNode>, #[serde(default)] local_states:Vec<LocalStateSlot>, #[serde(default)] host_values:Vec<HostValue>, #[serde(default)] state_transitions:Vec<StateTransition>, #[serde(default)] toggles:Vec<ToggleNode>, #[serde(default)] dependency_edges:Vec<DependencyEdge> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct ElementNode { id:String, tag:String, attributes:Vec<AttributeNode>, children:Vec<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct AttributeNode { name:String, static_value:Option<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct TextNode { id:String, static_value:Option<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct BindingNode { id:String, kind:String, target_id:String, attribute_name:Option<String>, expression_id:Option<String> }
#[derive(Clone, Deserialize)] struct ExpressionNode { id:String, expression:Value }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct EventNode { id:String, #[serde(rename="type")] event_type:String, target_id:String, action_id:String, #[serde(default)] field:Option<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct LoopNode { id:String, parent_id:String, input_id:Option<String>, query_id:Option<String>, row_template_root_element_id:Option<String>, #[serde(default)] rows:Vec<StaticLoopRow> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct StaticLoopRow { root_element_id:String }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct LocalStateSlot { id:String, name:String, initial_value:String, values:Vec<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct HostValue { kind:String, query:String }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct StateTransition { event_id:String, state_slot_id:String, kind:String }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct DependencyEdge { from_id:String, to_id:String, kind:String }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct ToggleValue { static_value:Option<String> }
#[derive(Clone, Deserialize)] #[serde(rename_all="camelCase")]
struct ToggleNode { root_element_id:String, input_element_id:String, indicator_element_id:Option<String>, action_id:Option<String>, checked:Option<ToggleValue>, default_checked:Option<ToggleValue>, indeterminate:Option<ToggleValue>, disabled:Option<ToggleValue>, read_only:Option<ToggleValue> }
#[derive(Deserialize)] #[serde(tag="type", rename_all="camelCase", rename_all_fields="camelCase")]
enum RuntimeDelta { Update { input_id:String, row_key:String, changes:HashMap<String,Value> }, Insert { input_id:String, row_key:String, row:HashMap<String,Value>, before_row_key:Option<String> }, Remove { input_id:String, row_key:String }, Move { input_id:String, row_key:String, before_row_key:Option<String> } }
#[derive(Default, Serialize, Deserialize)] #[serde(rename_all="camelCase")]
struct UpdateMetrics { dom_operations:u32, nodes_touched:u32, bindings_touched:u32, wasm_dom_us:f64 }
#[derive(Default, Serialize)] #[serde(rename_all="camelCase")]
struct MountMetrics { decode_us:f64, static_mount_us:f64, row_program_execute_us:f64, row_state_registration_us:f64, fragment_append_us:f64, program_compile_us:f64, program_revision:Option<String>, instruction_count:u32, compiled_expression_count:u32, field_slot_count:u32, binding_program_count:u32, average_row_program_execute_us:f64, row_count:u32, created_elements:u32, created_texts:u32, bindings:u32, dom_operations:u32 }

#[derive(Clone)] enum Literal { Null, Bool(bool), Number(serde_json::Number), String(String) }
#[derive(Clone)] enum CompiledExpr { Literal(Literal), Identifier(String), Member{object:Box<CompiledExpr>,property:String}, Binary{op:String,left:Box<CompiledExpr>,right:Box<CompiledExpr>}, Logical{op:String,left:Box<CompiledExpr>,right:Box<CompiledExpr>}, Conditional{test:Box<CompiledExpr>,consequent:Box<CompiledExpr>,alternate:Box<CompiledExpr>}, Template(Vec<TemplatePart>), Array(Vec<CompiledExpr>), Object(Vec<(String,CompiledExpr)>), Intrinsic(Vec<CompiledExpr>) }
#[derive(Clone)] enum TemplatePart { Static(String), Expr(CompiledExpr) }
#[derive(Clone, Copy)] enum TargetKind { Text, Attribute }
#[allow(dead_code)]
#[derive(Clone)] struct BindingProgram { node_slot:usize, target_kind:TargetKind, attribute_slot:Option<usize>, expression_slot:usize, field_slots:Vec<usize> }
#[derive(Clone)] struct RuntimeEvent { action_id:String, event_type:String, field:Option<String> }
#[derive(Clone)] enum RowInstruction { CreateElement{slot:usize,tag:String,static_attributes:Vec<(String,String)>,event:Option<RuntimeEvent>}, CreateText{slot:usize,static_value:String}, Append{parent_slot:usize,child_slot:usize}, Bind{binding_slot:usize,slot:usize,target_kind:TargetKind,attribute_slot:Option<usize>,expression_slot:usize} }
#[derive(Clone)] struct RowProgram { parent_node_id:String, root_slot:usize, node_slot_count:usize, instructions:Vec<RowInstruction>, bindings:Vec<BindingProgram>, fields:Vec<String>, field_slots:HashMap<String,usize>, bindings_by_field:Vec<Vec<usize>>, attributes:Vec<String>, element_count_per_row:u32, text_count_per_row:u32 }
struct ApplicationProgram { revision:Option<String>, compiled_expressions:Vec<CompiledExpr>, loops_by_input:HashMap<String,RowProgram>, compile_us:f64 }
#[derive(Clone)] struct LiveBinding { node:Node, target_kind:TargetKind, attribute_slot:Option<usize>, expression_slot:usize }
struct RowInstance { root:Node, values:HashMap<String,Value>, bindings:Vec<LiveBinding>, binding_marks:Vec<u32>, binding_mark_generation:u32 }
#[derive(Clone)] struct StaticBinding { node:Node, kind:TargetKind, attribute:String, expression:CompiledExpr }
struct ThemeShared { mode:String, media:MediaQueryList, bindings:Vec<StaticBinding>, media_listener:Option<Closure<dyn FnMut(Event)>> }
struct ToggleShared { input:HtmlInputElement, root:Element, indicator:Option<Element>, state:String, controlled:bool, read_only:bool, disabled:bool, action_id:Option<String> }

#[wasm_bindgen]
pub struct Runtime { application:RefCell<Option<ApplicationIr>>, program:RefCell<Option<ApplicationProgram>>, mounted:RefCell<HashMap<String,Node>>, rows:RefCell<HashMap<String,HashMap<String,RowInstance>>>, themes:RefCell<Vec<Rc<RefCell<ThemeShared>>>>, toggles:RefCell<Vec<Rc<RefCell<ToggleShared>>>>, click_listeners:RefCell<Vec<(Element, String, Closure<dyn FnMut(Event)>)>>, disposed:RefCell<bool> }
#[wasm_bindgen]
impl Runtime {
 #[wasm_bindgen(constructor)] pub fn new()->Runtime { Runtime { application:RefCell::new(None), program:RefCell::new(None), mounted:RefCell::new(HashMap::new()), rows:RefCell::new(HashMap::new()), themes:RefCell::new(Vec::new()), toggles:RefCell::new(Vec::new()), click_listeners:RefCell::new(Vec::new()), disposed:RefCell::new(false) } }
 pub fn load_application(&self, ir:JsValue)->Result<(),JsValue> { let app:ApplicationIr=serde_wasm_bindgen::from_value(ir).map_err(err)?; let program=compile_program(&app)?; self.program.replace(Some(program)); self.application.replace(Some(app)); Ok(()) }
 pub fn mount(&self, root:Element)->Result<JsValue,JsValue> {
  self.clear_live_resources()?; *self.disposed.borrow_mut()=false;
  let start=now(); let app=self.app()?; let doc=document()?; let mut nodes:HashMap<String,Node>=HashMap::new();
  for e in &app.elements { nodes.insert(e.id.clone(),create_dom_element(&doc,&e.tag)?.into()); }
  for t in &app.texts { nodes.insert(t.id.clone(),doc.create_text_node(t.static_value.as_deref().unwrap_or("")).into()); }
  for e in &app.elements { let element:Element=nodes[&e.id].clone().dyn_into().map_err(|_|JsValue::from_str("element"))?; element.set_attribute("data-runtime-node", &e.id)?; for a in &e.attributes { if let Some(v)=&a.static_value { element.set_attribute(normalize_attribute(&a.name),v)?; } } if let Some(event)=app.events.iter().find(|event| event.target_id == e.id) { element.set_attribute("data-runtime-action", &event.action_id)?; element.set_attribute("data-runtime-event", &event.event_type)?; } for child in &e.children { if !app.loops.iter().any(|l|l.id==*child) { element.append_child(&nodes[child])?; } } }
  // Literal-array maps are lowered as static loop rows. They are already in
  // the IR's element table, so mount them once without creating row state.
  for loop_node in &app.loops { if loop_node.input_id.is_none() && loop_node.query_id.is_none() { let parent:Element=nodes[&loop_node.parent_id].clone().dyn_into().map_err(|_|JsValue::from_str("static loop parent"))?; for row in &loop_node.rows { parent.append_child(&nodes[&row.root_element_id])?; } } }
  root.set_inner_html(""); root.append_child(&nodes[&app.root_element_id])?; self.mounted.replace(nodes); self.rows.replace(HashMap::new()); self.install_themes(&app)?; self.install_toggles(&app)?;
  let program=self.program.borrow(); let cached=program.as_ref().ok_or_else(||JsValue::from_str("application program missing"))?;
  let instruction_count=cached.loops_by_input.values().map(|p|p.instructions.len()).sum::<usize>(); let field_slot_count=cached.loops_by_input.values().map(|p|p.fields.len()).sum::<usize>(); let binding_program_count=cached.loops_by_input.values().map(|p|p.bindings.len()).sum::<usize>();
  finish_mount(MountMetrics{static_mount_us:(now()-start)*1000.0,program_compile_us:cached.compile_us,program_revision:cached.revision.clone(),instruction_count:instruction_count as u32,compiled_expression_count:cached.compiled_expressions.len() as u32,field_slot_count:field_slot_count as u32,binding_program_count:binding_program_count as u32,created_elements:app.elements.len() as u32,created_texts:app.texts.len() as u32,bindings:app.bindings.len() as u32,dom_operations:1,..Default::default()})
 }
 pub fn adopt(&self, root:Element)->Result<JsValue,JsValue> {
  self.clear_live_resources()?; *self.disposed.borrow_mut()=false;
  let start=now(); let app=self.app()?;
  if root.get_attribute("data-runtime-revision").unwrap_or_default()!=app.revision.clone().unwrap_or_default() { return finish_adoption(None); }
  let static_ids=static_node_ids(&app);
  let mut nodes:HashMap<String,Node>=HashMap::new();
  for element_node in &app.elements {
   if !static_ids.contains(&element_node.id) { continue; }
   let selector=format!("[data-runtime-node=\"{}\"]",element_node.id);
   let Some(element)=root.query_selector(&selector)? else { return finish_adoption(None); };
   if element.tag_name().to_ascii_lowercase()!=element_node.tag.to_ascii_lowercase() { return finish_adoption(None); }
   nodes.insert(element_node.id.clone(),element.into());
  }
  let text_nodes=text_anchor_nodes(&root);
  for text_node in &app.texts {
   if !static_ids.contains(&text_node.id) { continue; }
   let Some(node)=text_nodes.get(&text_node.id) else { return finish_adoption(None); };
   nodes.insert(text_node.id.clone(),node.clone());
  }
  self.mounted.replace(nodes); self.rows.replace(HashMap::new()); self.install_themes(&app)?; self.install_toggles(&app)?;
  let program=self.program.borrow(); let cached=program.as_ref().ok_or_else(||JsValue::from_str("application program missing"))?;
  let instruction_count=cached.loops_by_input.values().map(|p|p.instructions.len()).sum::<usize>(); let field_slot_count=cached.loops_by_input.values().map(|p|p.fields.len()).sum::<usize>(); let binding_program_count=cached.loops_by_input.values().map(|p|p.bindings.len()).sum::<usize>();
  finish_adoption(Some(MountMetrics{static_mount_us:(now()-start)*1000.0,program_compile_us:cached.compile_us,program_revision:cached.revision.clone(),instruction_count:instruction_count as u32,compiled_expression_count:cached.compiled_expressions.len() as u32,field_slot_count:field_slot_count as u32,binding_program_count:binding_program_count as u32,bindings:app.bindings.len() as u32,..Default::default()}))
 }
 pub fn dispose(&self)->Result<(),JsValue>{ if *self.disposed.borrow(){return Ok(());} *self.disposed.borrow_mut()=true; for theme in self.themes.borrow_mut().drain(..){dispose_theme(&theme)?;} self.toggles.borrow_mut().clear(); for (element,event,listener) in self.click_listeners.borrow_mut().drain(..){element.remove_event_listener_with_callback(&event,listener.as_ref().unchecked_ref())?;} self.rows.borrow_mut().clear(); self.mounted.borrow_mut().clear(); self.program.borrow_mut().take(); self.application.borrow_mut().take(); Ok(()) }
 pub fn initialize_input(&self, input_id:String, rows:JsValue)->Result<JsValue,JsValue> { let decode_start=now(); let input:Vec<HashMap<String,Value>>=serde_wasm_bindgen::from_value(rows).map_err(err)?; let decode_us=(now()-decode_start)*1000.0; let row_program=self.row_program(&input_id)?; let parent:Element=self.mounted.borrow().get(&row_program.parent_node_id).cloned().ok_or_else(||JsValue::from_str("loop parent missing"))?.dyn_into().map_err(|_|JsValue::from_str("loop parent"))?; let fragment=document()?.create_document_fragment(); let execute_start=now(); let mut instances=Vec::with_capacity(input.len()); for row in input { let key=value_string(row.get("id")); if self.rows.borrow().get(&input_id).and_then(|rows|rows.get(&key)).is_some(){continue;} let instance=self.execute_row(&row_program,row)?; if let Ok(element)=instance.root.clone().dyn_into::<Element>() { element.set_attribute("data-runtime-row-key",&key)?; } fragment.append_child(&instance.root)?; instances.push((key,instance)); } let row_program_execute_us=(now()-execute_start)*1000.0; let register_start=now(); let row_count=instances.len() as u32; let mut registry=self.rows.borrow_mut(); let target=registry.entry(input_id).or_default(); for (key,instance) in instances { target.insert(key,instance); } let row_state_registration_us=(now()-register_start)*1000.0; let append_start=now(); parent.append_child(&fragment)?; let fragment_append_us=(now()-append_start)*1000.0; finish_mount(MountMetrics{decode_us,row_program_execute_us,row_state_registration_us,fragment_append_us,row_count,created_elements:row_program.element_count_per_row*row_count,created_texts:row_program.text_count_per_row*row_count,bindings:row_program.bindings.len() as u32*row_count,average_row_program_execute_us:if row_count==0{0.0}else{row_program_execute_us/row_count as f64},dom_operations:1,..Default::default()}) }
 pub fn apply_delta(&self, delta:JsValue)->Result<JsValue,JsValue> { let start=now(); let d:RuntimeDelta=serde_wasm_bindgen::from_value(delta).map_err(err)?; let mut m=UpdateMetrics::default(); match d { RuntimeDelta::Update{input_id,row_key,changes}=>self.update_row(&input_id,&row_key,changes,&mut m)?, RuntimeDelta::Insert{input_id,row_key,row,before_row_key}=>self.insert_row(&input_id,row_key,row,before_row_key,&mut m)?, RuntimeDelta::Remove{input_id,row_key}=>self.remove_row(&input_id,&row_key,&mut m)?, RuntimeDelta::Move{input_id,row_key,before_row_key}=>self.move_row(&input_id,&row_key,before_row_key,&mut m)? }; m.wasm_dom_us=(now()-start)*1000.0; finish(m) }
 pub fn apply_deltas(&self, deltas:JsValue)->Result<JsValue,JsValue> { let values:Vec<RuntimeDelta>=serde_wasm_bindgen::from_value(deltas).map_err(err)?; let mut total=UpdateMetrics::default(); for value in values { let encoded=serde_wasm_bindgen::to_value(&delta_json(value)).map_err(err)?; let next:UpdateMetrics=serde_wasm_bindgen::from_value(self.apply_delta(encoded)?).map_err(err)?; total.dom_operations+=next.dom_operations; total.nodes_touched+=next.nodes_touched; total.bindings_touched+=next.bindings_touched; total.wasm_dom_us+=next.wasm_dom_us; } finish(total) }
}

impl Runtime {
 fn app(&self)->Result<ApplicationIr,JsValue>{self.application.borrow().clone().ok_or_else(||JsValue::from_str("loadApplication must be called first"))}
 fn clear_live_resources(&self)->Result<(),JsValue>{ for theme in self.themes.borrow_mut().drain(..){dispose_theme(&theme)?;} self.toggles.borrow_mut().clear(); for (element,event,listener) in self.click_listeners.borrow_mut().drain(..){element.remove_event_listener_with_callback(&event,listener.as_ref().unchecked_ref())?;} self.rows.borrow_mut().clear(); self.mounted.borrow_mut().clear(); Ok(()) }
 fn install_themes(&self,app:&ApplicationIr)->Result<(),JsValue>{
  let mut expressions:HashMap<String,CompiledExpr>=HashMap::new(); for entry in &app.expressions { expressions.insert(entry.id.clone(),compile_expr(&entry.expression).map_err(err)?); }
  for transition in &app.state_transitions {
   if transition.kind!="theme-cycle" { continue; }
   let slot=app.local_states.iter().find(|slot|slot.id==transition.state_slot_id).ok_or_else(||JsValue::from_str("theme state slot missing"))?;
   if slot.name!="mode" || !slot.values.iter().all(|value|matches!(value.as_str(),"light"|"dark"|"auto")) { return Err(JsValue::from_str("unsupported local state slot")); }
   let event=app.events.iter().find(|event|event.id==transition.event_id).ok_or_else(||JsValue::from_str("theme event missing"))?;
   let host=app.host_values.iter().find(|host|host.kind=="media-query").ok_or_else(||JsValue::from_str("theme media host missing"))?;
   let media=web_sys::window().ok_or_else(||JsValue::from_str("window unavailable"))?.match_media(&host.query)?.ok_or_else(||JsValue::from_str("media query unavailable"))?;
   let button:Element=self.mounted.borrow().get(&event.target_id).cloned().ok_or_else(||JsValue::from_str("theme button missing"))?.dyn_into().map_err(|_|JsValue::from_str("theme button"))?;
   let binding_ids:HashSet<String>=app.dependency_edges.iter().filter(|edge|edge.kind=="local-state-to-binding"&&edge.from_id==slot.id).map(|edge|edge.to_id.clone()).collect();
   let mut bindings=Vec::new();
   for binding in app.bindings.iter().filter(|binding|binding_ids.contains(&binding.id)) { let node=self.mounted.borrow().get(&binding.target_id).cloned().ok_or_else(||JsValue::from_str("theme binding node missing"))?; let expression=expressions.get(binding.expression_id.as_ref().ok_or_else(||JsValue::from_str("theme binding expression missing"))?).cloned().ok_or_else(||JsValue::from_str("theme expression missing"))?; bindings.push(StaticBinding{node,kind:if binding.kind=="text"{TargetKind::Text}else{TargetKind::Attribute},attribute:binding.attribute_name.clone().unwrap_or_default(),expression}); }
   let shared=Rc::new(RefCell::new(ThemeShared{mode:read_theme_mode().unwrap_or_else(||slot.initial_value.clone()),media,bindings,media_listener:None}));
   apply_theme(&shared)?; sync_theme_subscription(&shared)?;
   let click_shared=shared.clone(); let click=Closure::wrap(Box::new(move |_event:Event| { let _=advance_theme(&click_shared); }) as Box<dyn FnMut(Event)>); button.add_event_listener_with_callback("click",click.as_ref().unchecked_ref())?;
   self.click_listeners.borrow_mut().push((button,"click".into(),click)); self.themes.borrow_mut().push(shared);
  } Ok(())
 }
 fn install_toggles(&self, app:&ApplicationIr)->Result<(),JsValue>{
  for toggle in &app.toggles {
   let input:HtmlInputElement=self.mounted.borrow().get(&toggle.input_element_id).cloned().ok_or_else(||JsValue::from_str("toggle input missing"))?.dyn_into().map_err(|_|JsValue::from_str("toggle input"))?;
   let root:Element=self.mounted.borrow().get(&toggle.root_element_id).cloned().ok_or_else(||JsValue::from_str("toggle root missing"))?.dyn_into().map_err(|_|JsValue::from_str("toggle root"))?;
   let indicator=toggle.indicator_element_id.as_ref().and_then(|id|self.mounted.borrow().get(id).cloned()).and_then(|node|node.dyn_into::<Element>().ok());
   let initial=toggle.checked.as_ref().or(toggle.default_checked.as_ref()).and_then(|v|v.static_value.clone()).unwrap_or_else(||"false".into());
   let shared=Rc::new(RefCell::new(ToggleShared{input:input.clone(),root:root.clone(),indicator,state:initial,controlled:toggle.checked.is_some(),read_only:toggle.read_only.as_ref().and_then(|v|v.static_value.as_deref())==Some("true"),disabled:toggle.disabled.as_ref().and_then(|v|v.static_value.as_deref())==Some("true"),action_id:toggle.action_id.clone()}));
   if toggle.indeterminate.as_ref().and_then(|v|v.static_value.as_deref())==Some("true") { shared.borrow_mut().state="mixed".into(); }
   apply_toggle(&shared)?;
   let next=shared.clone(); let listener=Closure::wrap(Box::new(move |event:Event| { let mut state=next.borrow_mut(); if state.disabled||state.read_only { event.prevent_default(); apply_toggle(&next).ok(); return; } let old=state.state.clone(); let proposed=if old=="mixed"{"true"}else if old=="true"{"false"}else{"true"}.to_string(); if state.controlled { event.prevent_default(); state.input.set_checked(old=="true"); state.input.set_indeterminate(old=="mixed"); if let Some(action)=&state.action_id { let _=state.root.set_attribute("data-runtime-action",action); } } else { state.state=proposed; drop(state); let _=apply_toggle(&next); } }) as Box<dyn FnMut(Event)>);
   input.add_event_listener_with_callback("click",listener.as_ref().unchecked_ref())?; self.click_listeners.borrow_mut().push((input.clone().into(),"click".into(),listener)); self.toggles.borrow_mut().push(shared);
  } Ok(())
 }
 fn row_program(&self,input:&str)->Result<RowProgram,JsValue>{self.program.borrow().as_ref().and_then(|p|p.loops_by_input.get(input)).cloned().ok_or_else(||JsValue::from_str(&format!("unknown input {input}")))}
 fn execute_row(&self, program:&RowProgram, values:HashMap<String,Value>)->Result<RowInstance,JsValue>{ let doc=document()?; let expressions=self.program.borrow().as_ref().ok_or_else(||JsValue::from_str("application program missing"))?.compiled_expressions.clone(); let mut slots:Vec<Option<Node>>=vec![None;program.node_slot_count]; let mut bindings=Vec::with_capacity(program.bindings.len()); for instruction in &program.instructions { match instruction { RowInstruction::CreateElement{slot,tag,static_attributes,event}=>{let e=doc.create_element(tag)?; for (name,value) in static_attributes { e.set_attribute(name,value)?; } if let Some(event)=event { e.set_attribute("data-runtime-action",&event.action_id)?; e.set_attribute("data-runtime-event",&event.event_type)?; if let Some(field)=&event.field { e.set_attribute("data-runtime-field",field)?; } } slots[*slot]=Some(e.into());}, RowInstruction::CreateText{slot,static_value}=>slots[*slot]=Some(doc.create_text_node(static_value).into()), RowInstruction::Append{parent_slot,child_slot}=>{let parent:Element=slots[*parent_slot].as_ref().ok_or_else(||JsValue::from_str("missing parent slot"))?.clone().dyn_into().map_err(|_|JsValue::from_str("non-element parent slot"))?; parent.append_child(slots[*child_slot].as_ref().ok_or_else(||JsValue::from_str("missing child slot"))?)?;}, RowInstruction::Bind{binding_slot,slot,target_kind,attribute_slot,expression_slot}=>{let node=slots[*slot].as_ref().ok_or_else(||JsValue::from_str("missing binding slot"))?.clone(); let value=eval(&expressions[*expression_slot],&values); apply_target(&node,*target_kind,*attribute_slot,program,&value)?; bindings.push(LiveBinding{node,target_kind:*target_kind,attribute_slot:*attribute_slot,expression_slot:*expression_slot}); debug_assert_eq!(*binding_slot,bindings.len()-1);} } } let root=slots[program.root_slot].take().ok_or_else(||JsValue::from_str("missing root slot"))?; Ok(RowInstance{root,values,binding_marks:vec![0;bindings.len()],bindings,binding_mark_generation:0}) }
 fn insert_row(&self,q:&str,key:String,row:HashMap<String,Value>,before:Option<String>,m:&mut UpdateMetrics)->Result<(),JsValue>{if self.rows.borrow().get(q).and_then(|r|r.get(&key)).is_some(){return Ok(());} let program=self.row_program(q)?; let instance=self.execute_row(&program,row)?;if let Ok(element)=instance.root.clone().dyn_into::<Element>(){element.set_attribute("data-runtime-row-key",&key)?;}let parent:Element=self.mounted.borrow().get(&program.parent_node_id).cloned().ok_or_else(||JsValue::from_str("loop parent missing"))?.dyn_into().map_err(|_|JsValue::from_str("loop parent"))?;let anchor=before.as_ref().and_then(|k|self.rows.borrow().get(q).and_then(|r|r.get(k)).map(|r|r.root.clone()));parent.insert_before(&instance.root,anchor.as_ref())?;self.rows.borrow_mut().entry(q.to_string()).or_default().insert(key,instance);m.dom_operations+=1;Ok(())}
 fn remove_row(&self,q:&str,key:&str,m:&mut UpdateMetrics)->Result<(),JsValue>{if let Some(row)=self.rows.borrow_mut().get_mut(q).and_then(|r|r.remove(key)){if let Some(parent)=row.root.parent_node(){parent.remove_child(&row.root)?;}m.dom_operations+=1;}Ok(())}
 fn move_row(&self,q:&str,key:&str,before:Option<String>,m:&mut UpdateMetrics)->Result<(),JsValue>{let program=self.row_program(q)?;let root=self.rows.borrow().get(q).and_then(|r|r.get(key)).map(|r|r.root.clone());let anchor=before.and_then(|k|self.rows.borrow().get(q).and_then(|r|r.get(&k)).map(|r|r.root.clone()));if let Some(root)=root{let parent:Element=self.mounted.borrow().get(&program.parent_node_id).cloned().ok_or_else(||JsValue::from_str("loop parent missing"))?.dyn_into().map_err(|_|JsValue::from_str("loop parent"))?;parent.insert_before(&root,anchor.as_ref())?;m.dom_operations+=1;}Ok(())}
 fn update_row(&self,q:&str,key:&str,changes:HashMap<String,Value>,m:&mut UpdateMetrics)->Result<(),JsValue>{let program=self.row_program(q)?;let expressions=self.program.borrow().as_ref().ok_or_else(||JsValue::from_str("application program missing"))?.compiled_expressions.clone();let mut rows=self.rows.borrow_mut();let Some(row)=rows.get_mut(q).and_then(|r|r.get_mut(key))else{return Ok(())};row.binding_mark_generation=row.binding_mark_generation.wrapping_add(1);if row.binding_mark_generation==0{row.binding_marks.fill(0);row.binding_mark_generation=1;}let generation=row.binding_mark_generation;let mut affected=Vec::new();for(field,value)in changes{row.values.insert(field.clone(),value);if let Some(field_slot)=program.field_slots.get(&field){for binding_slot in &program.bindings_by_field[*field_slot]{if row.binding_marks[*binding_slot]!=generation{row.binding_marks[*binding_slot]=generation;affected.push(*binding_slot);}}}}for binding_slot in affected{let binding=&row.bindings[binding_slot];let value=eval(&expressions[binding.expression_slot],&row.values);apply_target(&binding.node,binding.target_kind,binding.attribute_slot,&program,&value)?;m.dom_operations+=1;m.bindings_touched+=1;m.nodes_touched+=1;}Ok(())}
}

fn static_node_ids(app:&ApplicationIr)->HashSet<String> {
 let elements:HashMap<&str,&ElementNode>=app.elements.iter().map(|node|(node.id.as_str(),node)).collect();
 let loops:HashMap<&str,&LoopNode>=app.loops.iter().map(|node|(node.id.as_str(),node)).collect();
 fn visit(id:&str,elements:&HashMap<&str,&ElementNode>,loops:&HashMap<&str,&LoopNode>,ids:&mut HashSet<String>) {
  if let Some(loop_node)=loops.get(id) { if loop_node.input_id.is_none() && loop_node.query_id.is_none() { for row in &loop_node.rows { visit(&row.root_element_id,elements,loops,ids); } } return; }
  if let Some(element)=elements.get(id) { ids.insert(id.to_string()); for child in &element.children { visit(child,elements,loops,ids); } } else { ids.insert(id.to_string()); }
 }
 let mut ids=HashSet::new(); visit(&app.root_element_id,&elements,&loops,&mut ids); ids
}

fn text_anchor_nodes(root:&Element)->HashMap<String,Node> {
 fn visit(node:&Node,result:&mut HashMap<String,Node>) {
  let children=node.child_nodes();
  for index in 0..children.length() { let Some(child)=children.item(index) else { continue; }; if child.node_type()==Node::COMMENT_NODE { if let Some(value)=child.node_value() { if let Some(id)=value.strip_prefix("runtime-text:") { if let Some(text)=child.next_sibling() { result.insert(id.to_string(),text); } } } } visit(&child,result); }
 }
 let mut result=HashMap::new(); visit(&root.clone().into(),&mut result); result
}

fn compile_program(app:&ApplicationIr)->Result<ApplicationProgram,JsValue>{let start=now();let elements:HashMap<_,_>=app.elements.iter().cloned().map(|n|(n.id.clone(),n)).collect();let texts:HashMap<_,_>=app.texts.iter().cloned().map(|n|(n.id.clone(),n)).collect();let expr_sources:HashMap<_,_>=app.expressions.iter().map(|n|(n.id.clone(),&n.expression)).collect();let mut compiled_expressions=Vec::new();let mut expression_slots=HashMap::new();for expr in &app.expressions{expression_slots.insert(expr.id.clone(),compiled_expressions.len());compiled_expressions.push(compile_expr(&expr.expression).map_err(err)?);}let mut bindings_by_target:HashMap<String,Vec<&BindingNode>>=HashMap::new();for binding in &app.bindings{bindings_by_target.entry(binding.target_id.clone()).or_default().push(binding);}let events:HashMap<_,_>=app.events.iter().map(|e|(e.target_id.clone(),e)).collect();let mut loops_by_input=HashMap::new();for loop_node in &app.loops{let Some(input_id)=loop_node.input_id.as_ref().or(loop_node.query_id.as_ref()) else{continue};let root=loop_node.row_template_root_element_id.as_deref().ok_or_else(||JsValue::from_str(&format!("{}: missing row template",loop_node.id)))?;if !elements.contains_key(&loop_node.parent_id){return Err(JsValue::from_str(&format!("{}: missing parent {}",loop_node.id,loop_node.parent_id)));}let program=compile_row_program(input_id,&loop_node.parent_id,root,&elements,&texts,&bindings_by_target,&events,&expression_slots,&compiled_expressions)?;loops_by_input.insert(input_id.clone(),program);}let _=expr_sources;Ok(ApplicationProgram{revision:app.revision.clone(),compiled_expressions,loops_by_input,compile_us:(now()-start)*1000.0})}
fn compile_row_program(_query_id:&str,parent_id:&str,root_id:&str,elements:&HashMap<String,ElementNode>,texts:&HashMap<String,TextNode>,bindings_by_target:&HashMap<String,Vec<&BindingNode>>,events:&HashMap<String,&EventNode>,expression_slots:&HashMap<String,usize>,expressions:&[CompiledExpr])->Result<RowProgram,JsValue>{let mut program=RowProgram{parent_node_id:parent_id.to_string(),root_slot:0,node_slot_count:0,instructions:Vec::new(),bindings:Vec::new(),fields:Vec::new(),field_slots:HashMap::new(),bindings_by_field:Vec::new(),attributes:Vec::new(),element_count_per_row:0,text_count_per_row:0};let mut slots=HashMap::new();compile_template_node(root_id,None,elements,texts,bindings_by_target,events,expression_slots,expressions,&mut program,&mut slots)?;program.root_slot=*slots.get(root_id).ok_or_else(||JsValue::from_str("template root missing"))?;Ok(program)}
fn compile_template_node(id:&str,parent:Option<usize>,elements:&HashMap<String,ElementNode>,texts:&HashMap<String,TextNode>,bindings_by_target:&HashMap<String,Vec<&BindingNode>>,events:&HashMap<String,&EventNode>,expression_slots:&HashMap<String,usize>,expressions:&[CompiledExpr],program:&mut RowProgram,slots:&mut HashMap<String,usize>)->Result<usize,JsValue>{if slots.contains_key(id){return Err(JsValue::from_str(&format!("template node {id} is reused or cyclic")));}let slot=program.node_slot_count;program.node_slot_count+=1;slots.insert(id.to_string(),slot);if let Some(text)=texts.get(id){program.text_count_per_row+=1;program.instructions.push(RowInstruction::CreateText{slot,static_value:text.static_value.clone().unwrap_or_default()});}else{let element=elements.get(id).ok_or_else(||JsValue::from_str(&format!("template node {id} is unknown")))?;program.element_count_per_row+=1;let attrs=element.attributes.iter().filter_map(|a|a.static_value.as_ref().map(|v|(normalize_attribute(&a.name).to_string(),v.clone()))).collect();let event=events.get(id).map(|e|RuntimeEvent{action_id:e.action_id.clone(),event_type:e.event_type.clone(),field:e.field.clone()});program.instructions.push(RowInstruction::CreateElement{slot,tag:element.tag.clone(),static_attributes:attrs,event});for child in &element.children{let child_slot=compile_template_node(child,Some(slot),elements,texts,bindings_by_target,events,expression_slots,expressions,program,slots)?;program.instructions.push(RowInstruction::Append{parent_slot:slot,child_slot});}}if let Some(parent_slot)=parent{let _=parent_slot;}if let Some(bindings)=bindings_by_target.get(id){for binding in bindings{let expression_slot=if let Some(id)=&binding.expression_id{*expression_slots.get(id).ok_or_else(||JsValue::from_str(&format!("binding {} references unknown expression {id}",binding.id)))?}else{return Err(JsValue::from_str(&format!("binding {} has no expression id",binding.id)))};let target_kind=if binding.kind=="text"{TargetKind::Text}else if binding.kind=="attribute"{TargetKind::Attribute}else{return Err(JsValue::from_str(&format!("binding {} has unsupported kind {}",binding.id,binding.kind)))};let attribute_slot=if matches!(target_kind,TargetKind::Attribute){let name=normalize_attribute(binding.attribute_name.as_deref().ok_or_else(||JsValue::from_str(&format!("binding {} is missing attribute",binding.id)))?);Some(intern(&mut program.attributes,name))}else{None};let field_slots=dependencies(&expressions[expression_slot]).into_iter().map(|field|intern_field(program,field)).collect::<Vec<_>>();let binding_slot=program.bindings.len();program.bindings.push(BindingProgram{node_slot:slot,target_kind,attribute_slot,expression_slot,field_slots:field_slots.clone()});for field_slot in field_slots{program.bindings_by_field[field_slot].push(binding_slot);}program.instructions.push(RowInstruction::Bind{binding_slot,slot,target_kind,attribute_slot,expression_slot});}}Ok(slot)}

fn compile_expr(value:&Value)->Result<CompiledExpr,String>{let kind=value.get("kind").and_then(Value::as_str).ok_or("expression is missing kind")?;let expr=|v:&Value|compile_expr(v);match kind{"literal"=>Ok(CompiledExpr::Literal(match value.get("value").unwrap_or(&Value::Null){Value::Null=>Literal::Null,Value::Bool(v)=>Literal::Bool(*v),Value::Number(v)=>Literal::Number(v.clone()),Value::String(v)=>Literal::String(v.clone()),_=>return Err("literal must be scalar".into())})),"identifier"=>Ok(CompiledExpr::Identifier(value.get("name").and_then(Value::as_str).ok_or("identifier name")?.into())),"member"=>Ok(CompiledExpr::Member{object:Box::new(expr(value.get("object").ok_or("member object")?)?),property:value.get("property").and_then(Value::as_str).ok_or("member property")?.into()}),"binary"=>Ok(CompiledExpr::Binary{op:value.get("op").and_then(Value::as_str).ok_or("binary op")?.into(),left:Box::new(expr(value.get("left").ok_or("binary left")?)?),right:Box::new(expr(value.get("right").ok_or("binary right")?)?)}),"logical"=>Ok(CompiledExpr::Logical{op:value.get("op").and_then(Value::as_str).ok_or("logical op")?.into(),left:Box::new(expr(value.get("left").ok_or("logical left")?)?),right:Box::new(expr(value.get("right").ok_or("logical right")?)?)}),"conditional"=>Ok(CompiledExpr::Conditional{test:Box::new(expr(value.get("test").ok_or("conditional test")?)?),consequent:Box::new(expr(value.get("consequent").ok_or("conditional consequent")?)?),alternate:Box::new(expr(value.get("alternate").ok_or("conditional alternate")?)?)}),"template"=>Ok(CompiledExpr::Template(value.get("parts").and_then(Value::as_array).ok_or("template parts")?.iter().map(|p|if let Some(s)=p.as_str(){Ok(TemplatePart::Static(s.into()))}else{expr(p).map(TemplatePart::Expr)}).collect::<Result<_,_>>()?)),"array"=>Ok(CompiledExpr::Array(value.get("items").and_then(Value::as_array).ok_or("array items")?.iter().map(expr).collect::<Result<_,_>>()?)),"object"=>Ok(CompiledExpr::Object(value.get("entries").and_then(Value::as_array).ok_or("object entries")?.iter().map(|e|Ok((e.get("key").and_then(Value::as_str).ok_or("object key")?.into(),expr(e.get("value").ok_or("object value")?)?))).collect::<Result<_,String>>()?)),"intrinsic"=>Ok(CompiledExpr::Intrinsic(value.get("args").and_then(Value::as_array).ok_or("intrinsic args")?.iter().map(expr).collect::<Result<_,_>>()?)),_=>Err(format!("unsupported expression kind {kind}"))}}
fn dependencies(expr:&CompiledExpr)->Vec<String>{let mut fields=HashSet::new();fn visit(expr:&CompiledExpr,fields:&mut HashSet<String>){match expr{CompiledExpr::Identifier(name)=>{if name!="todo"{fields.insert(name.clone());}},CompiledExpr::Member{object,property}=>{if matches!(object.as_ref(),CompiledExpr::Identifier(name) if name=="todo"){fields.insert(property.clone());}else{visit(object,fields);}},CompiledExpr::Binary{left,right,..}|CompiledExpr::Logical{left,right,..}=>{visit(left,fields);visit(right,fields);},CompiledExpr::Conditional{test,consequent,alternate}=>{visit(test,fields);visit(consequent,fields);visit(alternate,fields);},CompiledExpr::Template(parts)=>for part in parts{if let TemplatePart::Expr(expr)=part{visit(expr,fields)}},CompiledExpr::Array(items)|CompiledExpr::Intrinsic(items)=>for item in items{visit(item,fields)},CompiledExpr::Object(entries)=>for(_,item)in entries{visit(item,fields)},CompiledExpr::Literal(_)=>{}}}visit(expr,&mut fields);let mut fields=fields.into_iter().collect::<Vec<_>>();fields.sort();fields}
fn eval(expr:&CompiledExpr,row:&HashMap<String,Value>)->Value{match expr{CompiledExpr::Literal(v)=>match v{Literal::Null=>Value::Null,Literal::Bool(v)=>Value::Bool(*v),Literal::Number(v)=>Value::Number(v.clone()),Literal::String(v)=>Value::String(v.clone())},CompiledExpr::Identifier(name)=>row.get(name).cloned().unwrap_or(Value::Null),CompiledExpr::Member{object,property}=>{if matches!(object.as_ref(),CompiledExpr::Identifier(name) if name=="todo"){row.get(property).cloned().unwrap_or(Value::Null)}else{eval(object,row).get(property).cloned().unwrap_or(Value::Null)}},CompiledExpr::Binary{op,left,right}=>binary(op,eval(left,row),eval(right,row)),CompiledExpr::Logical{op,left,right}=>{let left=eval(left,row);if op=="&&"{if truthy(&left){eval(right,row)}else{left}}else if op=="||"{if truthy(&left){left}else{eval(right,row)}}else if left.is_null(){eval(right,row)}else{left}},CompiledExpr::Conditional{test,consequent,alternate}=>if truthy(&eval(test,row)){eval(consequent,row)}else{eval(alternate,row)},CompiledExpr::Template(parts)=>Value::String(parts.iter().map(|part|match part{TemplatePart::Static(v)=>v.clone(),TemplatePart::Expr(expr)=>value_string(Some(&eval(expr,row)))}).collect()),CompiledExpr::Array(items)=>Value::Array(items.iter().map(|e|eval(e,row)).collect()),CompiledExpr::Object(entries)=>Value::Object(entries.iter().map(|(k,e)|(k.clone(),eval(e,row))).collect()),CompiledExpr::Intrinsic(args)=>Value::String(class_values(args,row).join(" "))}}
fn binary(op:&str,left:Value,right:Value)->Value{match op{"+"=>Value::String(format!("{}{}",value_string(Some(&left)),value_string(Some(&right)))),"=="|"==="=>Value::Bool(left==right),"!="|"!=="=>Value::Bool(left!=right),">"=>Value::Bool(left.as_f64().unwrap_or(0.0)>right.as_f64().unwrap_or(0.0)),">="=>Value::Bool(left.as_f64().unwrap_or(0.0)>=right.as_f64().unwrap_or(0.0)),"<"=>Value::Bool(left.as_f64().unwrap_or(0.0)<right.as_f64().unwrap_or(0.0)),"<="=>Value::Bool(left.as_f64().unwrap_or(0.0)<=right.as_f64().unwrap_or(0.0)),_=>Value::Null}}
fn class_values(values:&[CompiledExpr],row:&HashMap<String,Value>)->Vec<String>{let mut out=Vec::new();for value in values{let value=eval(value,row);if let Some(v)=value.as_str(){if !v.is_empty(){out.push(v.into())}}else if let Some(items)=value.as_array(){for item in items{if let Some(v)=item.as_str(){out.push(v.into())}}}else if let Some(entries)=value.as_object(){for(key,value)in entries{if truthy(value){out.push(key.clone())}}}}out}
fn apply_target(node:&Node,kind:TargetKind,attribute_slot:Option<usize>,program:&RowProgram,value:&Value)->Result<(),JsValue>{if matches!(kind,TargetKind::Text){node.clone().dyn_into::<web_sys::Text>().map_err(|_|JsValue::from_str("text target"))?.set_data(&value_string(Some(value)));return Ok(())}let element:Element=node.clone().dyn_into().map_err(|_|JsValue::from_str("attribute target"))?;let name=&program.attributes[attribute_slot.ok_or_else(||JsValue::from_str("attribute slot missing"))?];if name=="checked"{if let Ok(input)=element.clone().dyn_into::<HtmlInputElement>(){input.set_checked(value.as_bool().unwrap_or(false));return Ok(())}}if name=="value"{if let Ok(input)=element.clone().dyn_into::<HtmlInputElement>(){input.set_value(&value_string(Some(value)));return Ok(())}}if value.as_bool()==Some(false){element.remove_attribute(name)?}else{element.set_attribute(name,&value_string(Some(value)))?}Ok(())}
fn apply_static_binding(binding:&StaticBinding,values:&HashMap<String,Value>)->Result<(),JsValue>{let value=eval(&binding.expression,values);if matches!(binding.kind,TargetKind::Text){binding.node.clone().dyn_into::<web_sys::Text>().map_err(|_|JsValue::from_str("static text target"))?.set_data(&value_string(Some(&value)));return Ok(());}let element:Element=binding.node.clone().dyn_into().map_err(|_|JsValue::from_str("static attribute target"))?;let name=normalize_attribute(&binding.attribute);if value.as_bool()==Some(false){element.remove_attribute(name)?}else{element.set_attribute(name,&value_string(Some(&value)))?}Ok(())}
fn apply_toggle(shared:&Rc<RefCell<ToggleShared>>)->Result<(),JsValue>{let state=shared.borrow();let checked=state.state=="true";let mixed=state.state=="mixed";state.input.set_checked(checked);state.input.set_indeterminate(mixed);state.input.set_disabled(state.disabled);state.input.set_read_only(state.read_only);state.input.set_attribute("aria-checked",if mixed{"mixed"}else if checked{"true"}else{"false"})?;state.root.set_attribute("data-state",&state.state)?;if state.disabled{state.root.set_attribute("data-disabled","")?;}else{state.root.remove_attribute("data-disabled")?;}if state.read_only{state.root.set_attribute("data-readonly","")?;}else{state.root.remove_attribute("data-readonly")?;}if let Some(indicator)=&state.indicator{indicator.set_attribute("data-state",&state.state)?;if checked||mixed{indicator.remove_attribute("hidden")?;}else{indicator.set_attribute("hidden","")?;}}Ok(())}
fn read_theme_mode()->Option<String>{let storage=web_sys::window()?.local_storage().ok()??;let value=storage.get_item("theme").ok()??;if matches!(value.as_str(),"light"|"dark"|"auto"){Some(value)}else{None}}
fn apply_theme(shared:&Rc<RefCell<ThemeShared>>)->Result<(),JsValue>{let theme=shared.borrow();let resolved=if theme.mode=="auto"{if theme.media.matches(){"dark"}else{"light"}}else{theme.mode.as_str()};let root:HtmlElement=document()?.document_element().ok_or_else(||JsValue::from_str("document root unavailable"))?.dyn_into().map_err(|_|JsValue::from_str("document root"))?;root.class_list().remove_1("light")?;root.class_list().remove_1("dark")?;root.class_list().add_1(resolved)?;if theme.mode=="auto"{root.remove_attribute("data-theme")?;}else{root.set_attribute("data-theme",&theme.mode)?;}root.style().set_property("color-scheme",resolved)?;let mut values=HashMap::new();values.insert("mode".into(),Value::String(theme.mode.clone()));for binding in &theme.bindings{apply_static_binding(binding,&values)?;}Ok(())}
fn sync_theme_subscription(shared:&Rc<RefCell<ThemeShared>>)->Result<(),JsValue>{let mut theme=shared.borrow_mut();let active=theme.mode=="auto";if !active { if let Some(listener)=theme.media_listener.take(){theme.media.remove_event_listener_with_callback("change",listener.as_ref().unchecked_ref())?;} return Ok(()); }if theme.media_listener.is_none(){let next=shared.clone();let listener=Closure::wrap(Box::new(move |_event:Event|{let _=apply_theme(&next);}) as Box<dyn FnMut(Event)>);theme.media.add_event_listener_with_callback("change",listener.as_ref().unchecked_ref())?;theme.media_listener=Some(listener);}Ok(())}
fn advance_theme(shared:&Rc<RefCell<ThemeShared>>)->Result<(),JsValue>{let next={let theme=shared.borrow();match theme.mode.as_str(){"light"=>"dark","dark"=>"auto",_=>"light"}}.to_string();shared.borrow_mut().mode=next.clone();if let Some(storage)=web_sys::window().and_then(|window|window.local_storage().ok()).flatten(){let _=storage.set_item("theme",&next);}apply_theme(shared)?;sync_theme_subscription(shared)}
fn dispose_theme(shared:&Rc<RefCell<ThemeShared>>)->Result<(),JsValue>{let mut theme=shared.borrow_mut();if let Some(listener)=theme.media_listener.take(){theme.media.remove_event_listener_with_callback("change",listener.as_ref().unchecked_ref())?;}Ok(())}
fn intern(items:&mut Vec<String>,value:&str)->usize{if let Some(index)=items.iter().position(|v|v==value){index}else{items.push(value.into());items.len()-1}}
fn intern_field(program:&mut RowProgram,field:String)->usize{if let Some(slot)=program.field_slots.get(&field){*slot}else{let slot=program.fields.len();program.fields.push(field.clone());program.field_slots.insert(field,slot);program.bindings_by_field.push(Vec::new());slot}}
fn normalize_attribute(name:&str)->&str{if name=="className"{"class"}else{name}}
fn truthy(value:&Value)->bool{!value.is_null()&&value.as_bool()!=Some(false)&&value.as_str()!=Some("")}
fn value_string(value:Option<&Value>)->String{match value{Some(Value::String(v))=>v.clone(),Some(v)=>v.to_string(),None=>String::new()}}
fn delta_json(value:RuntimeDelta)->Value{match value{RuntimeDelta::Update{input_id,row_key,changes}=>serde_json::json!({"type":"update","inputId":input_id,"rowKey":row_key,"changes":changes}),RuntimeDelta::Insert{input_id,row_key,row,before_row_key}=>serde_json::json!({"type":"insert","inputId":input_id,"rowKey":row_key,"row":row,"beforeRowKey":before_row_key}),RuntimeDelta::Remove{input_id,row_key}=>serde_json::json!({"type":"remove","inputId":input_id,"rowKey":row_key}),RuntimeDelta::Move{input_id,row_key,before_row_key}=>serde_json::json!({"type":"move","inputId":input_id,"rowKey":row_key,"beforeRowKey":before_row_key})}}
fn create_dom_element(doc:&Document,tag:&str)->Result<Element,JsValue>{if matches!(tag,"svg"|"path"|"circle"|"rect"|"g"|"line"|"polyline"|"polygon"){doc.create_element_ns(Some("http://www.w3.org/2000/svg"),tag)}else{doc.create_element(tag)}}
fn document()->Result<Document,JsValue>{web_sys::window().and_then(|w|w.document()).ok_or_else(||JsValue::from_str("document unavailable"))}
fn now()->f64{web_sys::window().and_then(|w|w.performance()).map(|p|p.now()).unwrap_or(0.0)}
fn err<E:std::fmt::Display>(e:E)->JsValue{JsValue::from_str(&e.to_string())}
fn finish(m:UpdateMetrics)->Result<JsValue,JsValue>{serde_wasm_bindgen::to_value(&m).map_err(err)}
fn finish_mount(m:MountMetrics)->Result<JsValue,JsValue>{serde_wasm_bindgen::to_value(&m).map_err(err)}
fn finish_adoption(m:Option<MountMetrics>)->Result<JsValue,JsValue>{serde_wasm_bindgen::to_value(&m).map_err(err)}
