[package]
name = "plec-router"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = ["plec-ir/serde", "plec-schema/serde"]

[dependencies]
js-sys = { workspace = true }
plec-client = { path = "../plec-client", version = "0.1.0", default-features = false }
plec-dom = { path = "../plec-dom", version = "0.1.0", default-features = false }
plec-ir = { path = "../plec-ir", version = "0.1.0", default-features = false }
plec-schema = { path = "../plec-schema", version = "0.1.0", default-features = false }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
