/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompiledRouteImport } from './routes/compiled'
import { Route as CompiledSignalGardenRouteImport } from './routes/compiled-signal-garden'
import { Route as CompiledTodosRouteImport } from './routes/compiled-todos'
import { Route as ReactiveSignalGardenRouteImport } from './routes/reactive-signal-garden'
import { Route as ReactiveTodosRouteImport } from './routes/reactive-todos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompiledRoute = CompiledRouteImport.update({
  id: '/compiled',
  path: '/compiled',
  getParentRoute: () => rootRouteImport,
} as any)
const CompiledSignalGardenRoute = CompiledSignalGardenRouteImport.update({
  id: '/compiled-signal-garden',
  path: '/compiled-signal-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const CompiledTodosRoute = CompiledTodosRouteImport.update({
  id: '/compiled-todos',
  path: '/compiled-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactiveSignalGardenRoute = ReactiveSignalGardenRouteImport.update({
  id: '/reactive-signal-garden',
  path: '/reactive-signal-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactiveTodosRoute = ReactiveTodosRouteImport.update({
  id: '/reactive-todos',
  path: '/reactive-todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiled': typeof CompiledRoute
  '/compiled-signal-garden': typeof CompiledSignalGardenRoute
  '/compiled-todos': typeof CompiledTodosRoute
  '/reactive-signal-garden': typeof ReactiveSignalGardenRoute
  '/reactive-todos': typeof ReactiveTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiled': typeof CompiledRoute
  '/compiled-signal-garden': typeof CompiledSignalGardenRoute
  '/compiled-todos': typeof CompiledTodosRoute
  '/reactive-signal-garden': typeof ReactiveSignalGardenRoute
  '/reactive-todos': typeof ReactiveTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiled': typeof CompiledRoute
  '/compiled-signal-garden': typeof CompiledSignalGardenRoute
  '/compiled-todos': typeof CompiledTodosRoute
  '/reactive-signal-garden': typeof ReactiveSignalGardenRoute
  '/reactive-todos': typeof ReactiveTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compiled'
    | '/compiled-signal-garden'
    | '/compiled-todos'
    | '/reactive-signal-garden'
    | '/reactive-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compiled'
    | '/compiled-signal-garden'
    | '/compiled-todos'
    | '/reactive-signal-garden'
    | '/reactive-todos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compiled'
    | '/compiled-signal-garden'
    | '/compiled-todos'
    | '/reactive-signal-garden'
    | '/reactive-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompiledRoute: typeof CompiledRoute
  CompiledSignalGardenRoute: typeof CompiledSignalGardenRoute
  CompiledTodosRoute: typeof CompiledTodosRoute
  ReactiveSignalGardenRoute: typeof ReactiveSignalGardenRoute
  ReactiveTodosRoute: typeof ReactiveTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiled': {
      id: '/compiled'
      path: '/compiled'
      fullPath: '/compiled'
      preLoaderRoute: typeof CompiledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiled-signal-garden': {
      id: '/compiled-signal-garden'
      path: '/compiled-signal-garden'
      fullPath: '/compiled-signal-garden'
      preLoaderRoute: typeof CompiledSignalGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiled-todos': {
      id: '/compiled-todos'
      path: '/compiled-todos'
      fullPath: '/compiled-todos'
      preLoaderRoute: typeof CompiledTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactive-signal-garden': {
      id: '/reactive-signal-garden'
      path: '/reactive-signal-garden'
      fullPath: '/reactive-signal-garden'
      preLoaderRoute: typeof ReactiveSignalGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactive-todos': {
      id: '/reactive-todos'
      path: '/reactive-todos'
      fullPath: '/reactive-todos'
      preLoaderRoute: typeof ReactiveTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompiledRoute: CompiledRoute,
  CompiledSignalGardenRoute: CompiledSignalGardenRoute,
  CompiledTodosRoute: CompiledTodosRoute,
  ReactiveSignalGardenRoute: ReactiveSignalGardenRoute,
  ReactiveTodosRoute: ReactiveTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
